name: Run Predictor Script

on:
  schedule:
    - cron: "*/15 * * * *" # runs every 15 minutes (GitHub’s max frequency)
  workflow_dispatch: # lets you run manually in the Actions tab
  push:
    branches:
      - main # optional: run also on pushes to main

jobs:
  run-predictor:
    runs-on: ubuntu-latest
    env:
      FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt
      - name: Debug installed packages
        run: |
          python -m pip show numpy
          python -m pip show pandas
          python --version
      - name: Run predictor script
        run: |
          python backend/predictor.py
